name: blood_nation
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  icons_plus: ^5.0.0
  flutter_native_splash: ^2.3.11
  intl_phone_field: ^3.2.0
  pinput: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  timeline_tile: ^2.0.0
  provider: ^6.1.2
  http: ^1.2.0
  shared_preferences: ^2.2.3
  get: ^4.6.6
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

flutter_icons:
  android: "blood_nation"
  image_path: "assets/images/logo.png"